version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USERS_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USERS_DB}
    networks:
      - auth-service
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  records-db:
    image: postgres:15
    container_name: records-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_RECORS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_RECORS_PASSWORD}
      - POSTGRES_DB=${POSTGRES_RECORS_DB}
    networks:
      - records-service
    ports:
      - "5434:5432"
    volumes:
      - records_data:/var/lib/postgresql/data

  auth-service:
    image: auth_records/auth-service:latest
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USERS_USER}
      DB_PASS: ${POSTGRES_USERS_PASSWORD}
      DB_NAME: ${POSTGRES_USERS_DB}
      PORT: 8080
      HOST: 0.0.0.0
    ports:
      - 8081:8080
    expose:
      - 8080
      - 50051
    networks:
      - auth-service

  records-service:
    image: auth_records/records-service:latest
    container_name: records-service
    depends_on:
      - records-db
    environment:
      DB_HOST: records-db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_RECORS_USER}
      DB_PASS: ${POSTGRES_RECORS_PASSWORD}
      DB_NAME: ${POSTGRES_RECORS_DB}
      PORT: 8080
      GRPC_PORT: 50051
      HOST: 0.0.0.0
    expose:
      - 8080
      - 50051
    networks:
      - auth-service
      - records-service

volumes:
  auth_data:
  records_data:

networks:
  records-service:
    driver: bridge
  auth-service:
    driver: bridge
  records-db:
    driver: bridge
  auth-db:
    driver: bridge